import TravelPlanGrid, { PlanStop } from "@/components/TravelPlanGrid";

const demoPlan: PlanStop[] = [
  { id: "d1", day: 1, title: "POLANCO GALLERIES + DINNER", city: "MEXICO CITY", cityCode: "MEX",
    summary: "Jumex, Soumaya, Masaryk stroll, rooftop cocktail.",
    tags: ["art","luxury","food"],
    link: "https://maps.google.com/?q=Polanco%20Mexico%20City",
    checkInDate: "2025-11-06", checkOutDate: "2025-11-07", adults: 2, currency: "USD" },
  { id: "d2", day: 2, title: "CENTRO HISTÓRICO + ANTHROPOLOGY", city: "MEXICO CITY", cityCode: "MEX",
    summary: "Zócalo, Cathedral, murals, Anthropology Museum.",
    tags: ["history","culture"], link: "https://www.mna.inah.gob.mx/",
    checkInDate: "2025-11-07", checkOutDate: "2025-11-08", adults: 2, currency: "USD" },
  { id: "d3", day: 3, title: "ROMA/CONDESA + MERCADO ROMA", city: "MEXICO CITY", cityCode: "MEX",
    summary: "Gallery crawl, parks, Casa Lamm, mezcal.",
    tags: ["art","food"], link: "https://maps.google.com/?q=Roma%20Norte%20CDMX",
    checkInDate: "2025-11-08", checkOutDate: "2025-11-09", adults: 2, currency: "USD" },
  { id: "d4", day: 4, title: "TEOTIHUACAN + COYOACÁN", city: "MEXICO CITY", cityCode: "MEX",
    summary: "Pyramids at sunrise, Casa Azul, market snacks.",
    tags: ["ancient","museum"], link: "https://www.museofridakahlo.org.mx/",
    checkInDate: "2025-11-09", checkOutDate: "2025-11-10", adults: 2, currency: "USD" },
  { id: "d5", day: 5, title: "PUERTO VALLARTA • BEACH + MALECÓN", city: "PUERTO VALLARTA", cityCode: "PVR",
    summary: "Los Muertos Beach, sunset dinner, galleries.",
    tags: ["beach","relax"], link: "https://maps.google.com/?q=Zona%20Romantica%20Puerto%20Vallarta",
    checkInDate: "2025-11-10", checkOutDate: "2025-11-11", adults: 2, currency: "USD" },
];
